In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
linear = nn.Linear(4,3)
print(linear)
print(linear.bias)
print(linear.weight)

Linear(in_features=4, out_features=3, bias=True)
Parameter containing:
tensor([ 0.0119, -0.2464, -0.3079], requires_grad=True)
Parameter containing:
tensor([[ 0.1172,  0.2725,  0.2708, -0.2338],
        [-0.0904,  0.1889, -0.3766, -0.0966],
        [-0.4790, -0.0961, -0.3069,  0.1273]], requires_grad=True)


In [3]:
linear_input = torch.from_numpy(
    np.ones((1,4)).astype(np.float32)
    )

print(linear(linear_input))

tensor([[ 0.4386, -0.6212, -1.0626]], grad_fn=<AddmmBackward0>)


In [7]:
print(linear_input @ linear.weight.T + linear.bias)

tensor([[ 0.4386, -0.6212, -1.0626]], grad_fn=<AddBackward0>)
