In [1]:
import torch
import numpy as np
from numpy.linalg import norm, eigh

In [2]:
def svd(a):
    """
    Singular Value Decomposition (SVD) of a matrix A.

    :param A: Input matrix of shape (m, n)
    :return: U, S, V such that A ≈ U @ diag(S) @ V.T
    """
    eigen_values, eigen_vectors = eigh(a.T @ a)

    # Compute U Vectorize this:
    # u0 = A @ eigen_vectors[:, 0] / norm(A @ eigen_vectors[:, 0])
    # u1 = A @ eigen_vectors[:, 1] / norm(A @ eigen_vectors[:, 1])
    # u2 = A @ eigen_vectors[:, 2] / norm(A @ eigen_vectors[:, 2])

    u = np.dot(a, eigen_vectors)
    u /= np.linalg.norm(u, axis=0)

    # Compute V
    v = eigen_vectors

    # Compute diagonal matrix of singular values
    s = u.T @ a @ v

    return u, s, v

In [3]:
# Example usage
A = np.array([[-5, 2, 3], [2, 5, 1], [-3, 1, -5]])
A

array([[-5,  2,  3],
       [ 2,  5,  1],
       [-3,  1, -5]])

In [4]:
# Compute SVD using the custom function
U, S, V = svd(A)

In [17]:
# A = U @ S @ V.T
print(np.allclose(A, U @ S @ V.T))

True


In [7]:
# Compare with the built-in function
u, s, v = torch.svd(torch.from_numpy(A).float())

In [20]:
rank = torch.linalg.matrix_rank(torch.from_numpy(A).float())
u[:, :rank] @ torch.diag(s[:rank]) @ v[:, :rank].t()

tensor([[-5.0000,  2.0000,  3.0000],
        [ 2.0000,  5.0000,  1.0000],
        [-3.0000,  1.0000, -5.0000]])

# Validate outputs

### U

In [9]:
print(U)

[[-0.26726124  0.77151675  0.57735027]
 [ 0.80178373 -0.15430335  0.57735027]
 [ 0.53452248  0.6172134  -0.57735027]]


In [10]:
print(u)

tensor([[-0.5774, -0.7715,  0.2673],
        [-0.5773,  0.1543, -0.8018],
        [ 0.5774, -0.6172, -0.5345]])


### S

In [11]:
print(S)

[[ 5.00000000e+00  4.61927558e-17 -5.80878766e-17]
 [-1.78966239e-16  6.24499800e+00 -1.05776474e-15]
 [-2.24630037e-16 -1.28454465e-17  6.24499800e+00]]


In [12]:
print(s)

tensor([6.2450, 6.2450, 5.0000])


### V

In [13]:
print(V)

[[ 0.26726124 -0.96362411  0.        ]
 [ 0.80178373  0.22237479  0.5547002 ]
 [-0.53452248 -0.14824986  0.83205029]]


In [14]:
print(v)

tensor([[-0.0000,  0.9636, -0.2673],
        [-0.5547, -0.2224, -0.8018],
        [-0.8321,  0.1482,  0.5345]])
