In [1]:
import numpy as np

## One dimensional operations

In [5]:
# make 2 random integer matrices of size 3x3
A = np.random.randint(0, 10, (3, 3))
B = np.random.randint(0, 10, (3, 3))
print("Matrix A is: \n",A)
print('\n')
print("Matrix B is: \n",B)

Matrix A is: 
 [[3 6 2]
 [8 0 9]
 [4 8 0]]


Matrix B is: 
 [[4 9 6]
 [2 0 9]
 [8 9 4]]


In [8]:
# simple einsum example
es1 = np.einsum('i', A[0,:])
print("The sum of all elements in A is: ", es1)
print('\n')
print("The sum of all elements in A is: ", A[0,:])

The sum of all elements in A is:  [3 6 2]


The sum of all elements in A is:  [3 6 2]


In [11]:
# sum over the rows of A
es2 = np.einsum('i->', A[0,:])
print("The sum of all rows in A is: ", es2)
print('\n')
es2p = np.einsum('i->i', A[0,:])
print("The sum of all rows in A is: ", es2p)
print('\n')
print("The sum of all rows in A is: ", np.sum(A[0,:], axis=0))

The sum of all rows in A is:  11


The sum of all rows in A is:  [3 6 2]


The sum of all rows in A is:  11


In [13]:
# sample of element-wise multiplication
es3 = np.einsum('i,i->i', A[0,:], B[0,:])
print("The element-wise multiplication of A and B is: \n", es3)
print('\n')
print("The element-wise multiplication of A and B is: \n", A[0,:]*B[0,:])

The element-wise multiplication of A and B is: 
 [12 54 12]


The element-wise multiplication of A and B is: 
 [12 54 12]


In [15]:
# sample of inner product
es4 = np.einsum('i,i', A[0,:], B[0,:])
print("The inner product of A and B is: ", es4)
print('\n')
print("The inner product of A and B is: ", np.inner(A[0,:], B[0,:]))
print('\n')
print("The inner product of A and B is: ", np.dot(A[0,:], B[0,:]))

The inner product of A and B is:  78


The inner product of A and B is:  78


The inner product of A and B is:  78


In [21]:
# sample of outer product
es5 = np.einsum('i,j->ij', A[0,:], B[0,:])
print("The outer product of A and B is: \n", es5)
print('\n')
print("The outer product of A and B is: \n", np.outer(A[0,:], B[0,:]))
print('\n')
print(A[0,:], B[0,:])

The outer product of A and B is: 
 [[12 27 18]
 [24 54 36]
 [ 8 18 12]]


The outer product of A and B is: 
 [[12 27 18]
 [24 54 36]
 [ 8 18 12]]


[3 6 2] [4 9 6]


## Two Dimensional Operations

In [22]:
# return the matrix A
es6 = np.einsum('ij', A)
print("The matrix A is: \n", es6)
print('\n')
print("The matrix A is: \n", A)

The matrix A is: 
 [[3 6 2]
 [8 0 9]
 [4 8 0]]


The matrix A is: 
 [[3 6 2]
 [8 0 9]
 [4 8 0]]


In [23]:
# transpose of A
es7 = np.einsum('ji', A)
print("The transpose of A is: \n", es7)
print('\n')
print("The transpose of A is: \n", A.T)

The transpose of A is: 
 [[3 8 4]
 [6 0 8]
 [2 9 0]]


The transpose of A is: 
 [[3 8 4]
 [6 0 8]
 [2 9 0]]


In [25]:
# view diagonal of A
es8 = np.einsum('ii->i', A)
print("The diagonal of A is: ", es8)
print('\n')
print("The diagonal of A is: ", np.diag(A))

'''
By using the same index name for both dimensions, 'i', you are essentially instructing einsum to sum along the diagonal elements of A. 
Each element along the diagonal has the same index value for both rows and columns, and by specifying 'ii->i', 
you are telling einsum to collapse the two 'i' indices into a single 'i' index in the output array.
'''

The diagonal of A is:  [3 0 0]


The diagonal of A is:  [3 0 0]


"\nBy using the same index name for both dimensions, 'i', you are essentially instructing einsum to sum along the diagonal elements of A. \nEach element along the diagonal has the same index value for both rows and columns, and by specifying 'ii->i', \nyou are telling einsum to collapse the two 'i' indices into a single 'i' index in the output array.\n"

In [26]:
# view anti-diagonal of A
es9 = np.einsum('ii->i', A[:,::-1])
print("The anti-diagonal of A is: ", es9)
print('\n')
print("The anti-diagonal of A is: ", np.diag(A[:,::-1]))

The anti-diagonal of A is:  [2 0 4]


The anti-diagonal of A is:  [2 0 4]


In [29]:
# sum matrix A
es10 = np.einsum('ij->', A)
print("The sum of A is: ", es10)
print('\n')
print("The sum of A is: ", np.sum(A))

The sum of A is:  40


The sum of A is:  40


In [30]:
# sum matrix A along columns
es11 = np.einsum('ij->j', A)
print("The sum of A along columns is: ", es11)
print('\n')
print("The sum of A along columns is: ", np.sum(A, axis=0))

The sum of A along columns is:  [15 14 11]


The sum of A along columns is:  [15 14 11]


In [31]:
# element-wise multiplication of A and B
es12 = np.einsum('ij,ij->ij', A, B)
print("The element-wise multiplication of A and B is: \n", es12)
print('\n')
print("The element-wise multiplication of A and B is: \n", A*B)

The element-wise multiplication of A and B is: 
 [[12 54 12]
 [16  0 81]
 [32 72  0]]


The element-wise multiplication of A and B is: 
 [[12 54 12]
 [16  0 81]
 [32 72  0]]


In [35]:
# dot product of A and B
es13 = np.einsum('ij,jk', A, B)
print("The dot product of A and B is: ", es13)
print('\n')
print("The dot product of A and B is: ", np.dot(A, B))

The dot product of A and B is:  [[ 40  45  80]
 [104 153  84]
 [ 32  36  96]]


The dot product of A and B is:  [[ 40  45  80]
 [104 153  84]
 [ 32  36  96]]


In [37]:
# inner product of A and B
es14 = np.einsum('ij,kj->ik', A, B)
print("The inner product of A and B is: ", es14)
print('\n')
print("The inner product of A and B is: ", np.inner(A, B))

The inner product of A and B is:  [[ 78  24  86]
 [ 86  97 100]
 [ 88   8 104]]


The inner product of A and B is:  [[ 78  24  86]
 [ 86  97 100]
 [ 88   8 104]]


In [39]:
# dot product of A and B
es13 = np.einsum('ij,jk->ik', A, B)
print("The dot product of A and B is: ", es13)
print('\n')
print("The dot product of A and B is: ", np.dot(A, B))

The dot product of A and B is:  [[ 40  45  80]
 [104 153  84]
 [ 32  36  96]]


The dot product of A and B is:  [[ 40  45  80]
 [104 153  84]
 [ 32  36  96]]
